### ISSUE TITLE
How does this compare to Marvin?

### ISSUE THREAD

**Issue by Elijas** [shroominic/funcchain#10]
e.g.

https://www.askmarvin.ai/components/ai_model/

```
from marvin import ai_model
from pydantic import BaseModel, Field


@ai_model
class Location(BaseModel):
    city: str
    state: str = Field(..., description="The two-letter state abbreviation")

# We can now put pass unstructured context to this model.
Location("The Big Apple")
```

Can you expand on how this library compares to [Marvin](https://github.com/prefecthq/marvin)?

**Comment by shroominic** [comment]
Yeah, booth projects are similar, but if you get into the details, there are many differences.
The biggest I think is that funcchain is built on top of langchain so it's based on the same abstractions and you get all the benefits of using langchain without needing to know everything about it, e.g. langsmith logging, swap out models, caching, output parsing, ... 
There are also differences in features. Marvin has some features not included in but funcchain has also some not in Marvin like
- vision support
- union type function calling
- better mypy typing
- local model support via LlamaCpp
- error type fallback
- retry on validation errors

Please let me know if you think I am wrong about on one of these!
