### ISSUE TITLE
Custom pydantic models unpacking into prompt 

### ISSUE THREAD

**Issue by AriMKatz** [shroominic/funcchain#12]
Control representation by accessing fields, possibly doing some calculations and then interpolating into prompt

**Comment by shroominic** [comment]
Fixed the jinja syntax handling in v0.2.0a5 so this is working now 👍

https://github.com/shroominic/funcchain/blob/e24dc02338faa67bb3e3a9e9dad6ba5f4b934e03/examples/jinja.py#L12C1-L21C19

**Comment by shroominic** [comment]
will be released in v0.2 soon
