### ISSUE TITLE
`system` prompt is not used

### ISSUE THREAD

**Issue by ahuang11** [shroominic/funcchain#18]
If I'm not mistaken, I think system is never passed inside Signature history, thus never gets included.

https://github.com/shroominic/funcchain/blob/c0fad3ca9a35b53355181814ad994b160754e354/src/funcchain/syntax/executable.py#L44-L62

**Comment by shroominic** [comment]
i think you're right and im stupid

In the compile_runnable below i am adding it like this:
`context = [SystemMessage(content=system)] + context`

Its in general not optimal tho I want to add the system message via special input args at some point

**Comment by ahuang11** [comment]
Thanks! Let me know if there's anything I can help with.

**Comment by shroominic** [comment]
> "Its in general not optimal tho I want to add the system message via special input args at some point"
> 
> @shroominic should the system prompt be the default here for the docstring, and then input goes into a user message? Rational being that docstring, is well, basically a system prompt for that call. You can have a system with multiple system prompts since you'd want maximum steerability
@AriMKatz 

I think it depends on the fine tuning dataset of the model. From my experience the user message acts better as instruction and the system message is more like an optional steering vector but I thought about doing it booth ways and maybe we should do some more research like running benchmarks to see which method performs best
