### ISSUE TITLE
Cannot use dict as a type

### ISSUE THREAD

**Issue by ahuang11** [shroominic/funcchain#22]
```python
from pydantic import BaseModel, Field
from funcchain import chain

class Output(BaseModel):

    plot: str
    kwargs: dict = Field(default_factory=dict)


def get_kwargs(user_query: str) -> Output:
    """
    Translate the user query to a dictionary of kwargs
    """
    return chain()

get_kwargs("scatter(color='red')")
```

Results in
`AssertionError: Unrecognized schema: {'title': 'Kwargs', 'type': 'object'}`

<img width="941" alt="image" src="https://github.com/shroominic/funcchain/assets/15331990/33ee2aa6-36ab-4a87-b755-d6941eab2611">

**Comment by shroominic** [comment]
thanks will look into it! you can define other pydantic models and put them as type instead tho which is like a dict

**Comment by ahuang11** [comment]
Is it possible to define a model with unlimited/unexpected fields in pydantic, equivalent to **kwargs?

**Comment by shroominic** [comment]
yeah true this would be a usecase for a pure dict as type

**Comment by shroominic** [comment]
just pushed a fix that adds this to the schema converter for grammars!
the only issue is that the grammar is very open so the model might stumble across problems because its not tooo guided
