### ISSUE TITLE
Do not fallback to openai if a custom LLM is set

### ISSUE THREAD

**Issue by ahuang11** [shroominic/funcchain#26]
~If I'm not mistaken, Funcchain also works with CTransformers (since it might be more straightforward to install)~

```python
from funcchain import chain, settings
from pydantic import BaseModel
from langchain_community.llms.ctransformers import CTransformers


model = "TheBloke/Mistral-7B-Instruct-v0.1-GGUF"
model_file = "mistral-7b-instruct-v0.1.Q4_K_M.gguf"
settings.llm = CTransformers(model=model, model_file=model_file)


class Translated(BaseModel):

    chinese: str
    english: str
    french: str


def hello(text: str) -> Translated:
    """
    Translate text into three languages.
    """
    return chain()


hello("Hello!")
```

And maybe it works with other LLMs listed here too?

https://python.langchain.com/docs/integrations/llms/

**Comment by ahuang11** [comment]
Nevermind it doesn't work, it falls back to OpenAI, which is undesired

I believe this should be caught

https://github.com/shroominic/funcchain/blob/main/src/funcchain/model/defaults.py#L144-L164

**Comment by shroominic** [comment]
Just merged i think this should be resolved now let me know if not!

**Comment by shroominic** [comment]
btw CTransformers is natively not supported by funcchain so it does not utilise grammars for structured output and entirely relies on format instructions which work not that well for local models
