### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by janvandervegt** [shroominic/funcchain#5]
Hi,

Came across your package on Twitter and it looks very promising. I'll try it for my use case later today but I want to use it for synthetic data generation - requiring large throughput. Looking through the source code, it's not entirely clear to me how easy it is to run async pipelines with this - or what would be required to get there?

To clarify what I'm trying to do, I have a list of a 1000 structured inputs and want to generate the 1000 corresponding outputs. It's okay if a few fail to parse, but it's not okay if they need to run in sequence. I want it to be agnostic to using OpenAI (testing purposes, where the API calls would be async) or local LLMs (where the inputs should be batched in the Hugging Face model interface).

I'm not an expert on LangChain or on asynchronous Python but happy to contribute if `funcchain` is a good fit for my project.

**Comment by shroominic** [comment]
For async instead of importing chain you need to import achain.
`from funcchain import achain`
Then you can create an async function and you do return await achain().
For parallel compute asyncio.gather is a really good for this kind of tasks.
Let me know if the works for you :)
