### ISSUE TITLE
Warning message from the langchain

### ISSUE THREAD

**Issue by kwikiel** [shroominic/funcchain#6]
UserWarning: Importing llm_cache from langchain root module is no longer supported. Please use langchain.globals.set_llm_cache() / langchain.globals.get_llm_cache() instead.
 
 Steps to reproduce: this happens when running hello world application provided in the documentation.

**Comment by shroominic** [comment]
Hey are you running windows?

**Comment by shroominic** [comment]
Does it still show the error upgrading to the newest langchain version?

**Comment by kwikiel** [comment]
Seems it fixed it.
