### ISSUE TITLE
ImportError: cannot import name 'Self' from 'typing' 

### ISSUE THREAD

**Issue by kananimaulik26** [shroominic/funcchain#9]
ImportError: cannot import name 'Self' from 'typing' (/usr/local/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/typing.py)

**Comment by shroominic** [comment]
Hey, thanks for letting me know!
I just released v0.1.7 which should fix this issue :)
